### PR TITLE
 chore(maven): migrate to new artifacts.camunda.com

### PR DESCRIPTION
**Pull request by cmur2**
As announced, we need to switch to the new URL for Artifactory. See INFRA-3107

### CODE REVIEW

**Review by pihme — APPROVED** [review]
Thanks for the PR!

**Comment by pihme** [comment]
@cmur2 Did you sign the CLA?

**Comment by cmur2** [comment]
> @cmur2 Did you sign the CLA?

I thought I did previously but maybe it got lost, did now.

**Comment by pihme** [comment]
bors merge

**Pull request merged**
